version: '3.8'

services:
  backend:
    image: factored_fastapi_backend
    ports:
      - "8000:8000"

  frontend:
    image: factored_nextjs_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
